2020-11-25 11:42:47,865 ERROR: Exception on /reset_password_request [GET] [in c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Desktop\Projects\blog\app\routes.py", line 168, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Desktop\Projects\blog\app\templates\reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\Desktop\Projects\blog\app\templates\base.html", line 38, in top-level template code
    {% block content %}
  File "C:\Users\User\Desktop\Projects\blog\app\templates\reset_password_request.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'from' is undefined
2020-12-22 11:22:03,799 INFO: Microblog startup [in C:\Users\User\Desktop\Projects\blog\app\__init__.py:68]
2020-12-22 12:08:33,189 INFO: Microblog startup [in C:\Users\User\Desktop\Projects\blog\app\__init__.py:68]
2020-12-22 12:08:47,317 ERROR: Exception on /login [GET] [in c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Desktop\Projects\blog\app\routes.py", line 46, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Desktop\Projects\blog\app\templates\login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Desktop\Projects\blog\app\templates\base.html", line 11, in template
    {% blockcontent %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'blockcontent'.
2020-12-22 12:08:57,532 ERROR: Exception on /reset_password_request [GET] [in c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Desktop\Projects\blog\app\routes.py", line 168, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Desktop\Projects\blog\app\templates\reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\desktop\projects\blog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Desktop\Projects\blog\app\templates\base.html", line 11, in template
    {% blockcontent %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'blockcontent'.
